### ISSUE TITLE
怎么还原为js,wxml类型的文件

### ISSUE THREAD

**Issue by yangjisen** [zhuweiyou/wxapkg#4]
解压出来的全是html文件, 在app-service.js里面是一个大文件,怎么进行拆分成每个目录的文件呢?
我想得到wxml,wxss,js分开的独立文件

**Comment by zhuweiyou** [comment]
这个项目没实现这个功能,解包基本上是为了看一些关键逻辑,自行格式化app-service.js就可以看了.

**Comment by yangjisen** [comment]
> 这个项目没实现这个功能,解包基本上是为了看一些关键逻辑,自行格式化app-service.js就可以看了.

我看了一下以前node的代码，他们实现了还原这个操作，现在不行了，调试跟踪后是因为现在的app.json在分包的配置上有区别，修改后能够还原了
